sudo: required
dist: trusty
language: c
branches:
  only:
    - master
script:
  - "make $TASK"
matrix:
  include:
    - env: TASK=test
    - env: TASK=test CFLAGS="-O3 -std=c99"
    - env: TASK=bench
    - env: TASK=bench CFLAGS="-O3 -std=c99"
